CFLAGS=-Wall -c -ffreestanding -fno-pie -std=gnu99
LDFLAGS=
# These settings select the native compiler,
# which is likely to work on native linux-x86.

# everything except the bootloader should be compiled for 64 bit
CC=gcc -m64 -c -g
LD=ld -m elf_x86_64
#LD=ld -m elf_i386
AR=ar
OBJCOPY=objcopy
ISOGEN=genisoimage

# If you are compiling from another platform,
# then use the script build-cross-compiler.sh
# add cross/bin to your path, and uncomment these lines:
#CC=i686-elf-gcc
#LD=i686-elf-ld
#AR=i686-elf-ar
#OBJCOPY=i686-elf-objcopy

# If building on OSX, then install mkisofs via ports or brew
# and uncomment this:
#ISOGEN=mkisofs
