#pragma once
#include <stdint.h>
#include "sdt.h"

#define LAPIC_ID_REGISTER 0x20
#define LAPIC_VERSION_REGISTER 0x30
#define TASK_PRIORITY_REGISTER 0x80
#define ARBITRATION_PRIORITY_REGISTER 0x90
#define PROCESSOR_PRIORITY_REGISTER 0xA0
#define EOI_REGISTER 0xB0
#define REMOTE_READ_REGISTER 0xC0
#define LOCAL_DESTINATION_REGISTER 0xD0
#define DESTINATION_FORMAT_REGISTER 0xE0
#define SPURIOUS_INTERRUPT_VECTOR_REGISTER 0xF0
#define ERROR_STATUS_REGISTER 0x280
#define CMCI_REGISTER 0x2F0
#define LVT_TIMER_REGISTER 0x320
#define LVT_THERMAL_SENSOR_REGISTER 0x330
#define LVT_PERFORMANCE_COUNTER_REGISTER 0x340
#define LVT_LINT0_REGISTER 0x350
#define LVT_LINT1_REGISTER 0x360
#define LVT_ERROR_REGISTER 0x370
#define TIMER_INITIAL_COUNT_REGISTER 0x380
#define TIMER_CURRENT_COUNT_REGISTER 0x390
#define TIMER_DIVIDE_CONFIGURATION_REGISTER 0x3E0

void apic_setup();
void apic_write(uint16_t reg, uint32_t value);
uint32_t apic_read(uint16_t reg);

uint32_t ioapic_read(uint32_t reg);
void ioapic_write(uint32_t reg, uint32_t value);